name: .NET Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
           access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 3.1.x
         
      - name: Build
        run: dotnet publish PapyrusCs -c Release --self-contained --runtime win-x64
        
      - uses: vimtor/action-zip@v1
        with:
          files: PapyrusCs/bin/Release/netcoreapp3.1/win-x64/publish/
          dest: papyruscs-dotnetcore-0.6.${{github.run_number}}-win64.zip
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: papyruscs-dotnetcore-0.6.${{github.run_number}}-win64.zip
          path: papyruscs-dotnetcore-0.6.${{github.run_number}}-win64.zip
          if-no-files-found: error
          
      - name: Puts the release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "papyruscs-dotnetcore-0.6.${{github.run_number}}-win64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 0.6.${{github.run_number}}
          name: PapyrusCs - 0.6.${{github.run_number}}
          prerelease: true
          
